# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-24 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revroaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedurl',
            name='myList',
            field=models.TextField(null=True),
        ),
    ]
