# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-11-24 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revroaster', '0002_savedurl_mylist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedurl',
            name='myList',
        ),
        migrations.AddField(
            model_name='savedurl',
            name='negative',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='savedurl',
            name='positive',
            field=models.TextField(null=True),
        ),
    ]
